### ISSUE TITLE
Rename not working with windows 10 native client

### ISSUE THREAD

**Issue by nicolaspernoud** [wader/docker-webdav#1]
Hi,

Everything works fine while mounting the webdav share under windows 10, but for the rename which fails.

The log from the container is below : 

webdav_1               | 2018/04/22 08:51:12 r=&{MOVE /*old_name* HTTP/1.0 1 0 map[User-Agent:[Microsoft-WebDAV-MiniRedir/10.0.16299] Destination:[https://*domain*/*new_name*] Overwrite:[F] Translate:[f] Authorization:[Basic ************] Connection:[close] Content-Length:[0]] {} <nil> 0 [] true 127.0.0.1:3080 map[] map[] <nil> map[] 172.19.0.1:46240 /*old_name* <nil> <nil> <nil> 0xc42010eac0} err=webdav: invalid destination

**Comment by wader** [comment]
Hello! can you give some more info about your setup? behind reverse proxy? using prefix etc?

Looking at the source code and the log your provided i would guess it either fails on non-matching http  host header and destination url host or path ending up empty for some reason.

https://github.com/golang/net/blob/4bb47a1098b37d69980d96237e2ae4ff56bb5a95/webdav/webdav.go#L318

**Comment by nicolaspernoud** [comment]
Hi, thanks for answering. I am behind an nginx reverse proxy with the configuration below :

    server {
        server_name vault.*****.fr;
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        location / {
            proxy_pass http://127.0.0.1:3080;
            auth_basic "restricted";
            auth_basic_user_file /etc/nginx/htpasswd;
        }
    }

The container is started with a docker-compose with the configuration : 
```yaml
  webdav:
    image: mwader/webdav
    restart: unless-stopped
    volumes:
      - /data/hosted/private/password-vault:/webdav
    ports:
        - 3080:8080
```
Thanks !

**Comment by nicolaspernoud** [comment]
Hi again.

It actually works now by adding "proxy_set_header Host $http_host;" to the location directive.
I deleted the previous comment to not let misleading config extracts.

Thanks for your time !

**Comment by wader** [comment]
👍I guess the server could suppor X-Request-* headers to make things like this easier

**Comment by nicolaspernoud** [comment]
If someone is interested, the working nginx config is below.
The [^a-zA-Z0-9] bit si because nginx (or windows client ?) sometimes put a strange character at the end the header (probably a bug).

```
location / {
                        set $httpdest $http_destination;
                        if ( $http_destination ~* ^https(.*)[^a-zA-Z0-9]$ ) {
                                set $httpdest http$1;
                        }
                        proxy_set_header Destination $httpdest;
                        proxy_set_header Host $http_host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_pass http://127.0.0.1:3080;
}
```

**Comment by wader** [comment]
Hello, does the characters cause any problem? it could be lead to weird behaviour if the `Destination` header is modified in a proxy as it used by copy, move etc to know the destination. Usually URLs are suppose to be seen as "opaque" to clients (at least the path and query parts).  See https://tools.ietf.org/html/rfc4918#section-7.5.1 for example.

**Comment by nicolaspernoud** [comment]
It does, that's why I need to remove it : the destination header was scrambled and so the file renaming wouldn't work. Probably an nginx bug...
